import { useEffect, useState, type FormEvent } from "react";
import { ArrowUpRight, ArrowRight, Coffee, Cookie, Package, MessageCircle, Menu, X, Check, Plus, Minus } from "lucide-react";
import { SITE } from "./site";

const flavors = [
  { name: "Vanilla", image: "/images/cup-vanilla.jpg", tag: "A familiar favourite", description: "Explore a vanilla flavour direction for an easy sip-and-bite experience." },
  { name: "Cardamom", image: "/images/cup-cardamom.jpg", tag: "For your chai moments", description: "Explore a warm, spiced flavour direction for tea and chai service." },
  { name: "Chocolate", image: "/images/cup-choco.jpg", tag: "A little more indulgent", description: "Explore a chocolate flavour direction for coffee, celebrations and dessert service." },
];
const segments = [
  ["Cafés & chai shops", "/cafes", "Make the everyday coffee stop something to talk about."],
  ["Events & catering", "/events", "Give your guests another reason to remember the occasion."],
  ["Hotels & hospitality", "/hospitality", "Bring a different serving experience to your next service."],
  ["Wholesale & distribution", "/distributors", "Explore edible cups for the businesses you supply."],
];
const faqs = [
  ["What is an edible cup?", "It is a beverage cup that you can eat after finishing your drink. Request a sample to explore the texture, flavour and fit for your service."],
  ["Where are your cups made?", "Our edible cups are made in India and supplied by Sip N Snack Co. for business buyers in Canada and the USA."],
  ["Can I request a sample before buying in bulk?", "Yes. Share your business location and intended use. We will confirm sample availability and delivery arrangements before dispatch."],
  ["Are the cups vegan or gluten-free?", "Ask us for current ingredient and allergen information for the product you are considering. Do not assume the cups are vegan, gluten-free or suitable for an allergy without reviewing the product documentation."],
  ["Can I use them for hot drinks?", "Tell us your beverage and serving conditions. Review the product specifications and evaluate a sample before introducing the cups into your service."],
  ["How do I get wholesale pricing?", "Share your business type, location, estimated quantity and delivery date. We will prepare a quote and confirm product options, delivery and payment terms."],
];
const wa = `${SITE.whatsapp}?text=${encodeURIComponent("Hi Sip N Snack Co., I’m interested in learning more about your edible cups for my business.")}`;
export function Brand() { return <a className="brand" href="/" aria-label="Sip N Snack Co. home"><span className="brand-mark"><Coffee size={24} strokeWidth={1.5}/></span><span>Sip N Snack<span className="brand-co">CO. · BITE • SIP • SMILE</span></span></a>; }
const Cta = ({ children, href = "#inquiry", light = false }: { children: React.ReactNode; href?: string; light?: boolean }) => <a className={`button ${light ? "light" : "dark"}`} href={href}>{children}<ArrowUpRight size={18}/></a>;

function Inquiry({ flavor }: { flavor: string }) {
  const [type, setType] = useState("Sample request");
  const [phase, setPhase] = useState<"idle" | "sending" | "sent" | "error">("idle");
  useEffect(() => { const t = new URLSearchParams(window.location.search).get("interest"); if(t && ["Wholesale pricing", "Event inquiry", "Distribution partnership"].includes(t)) setType(t); }, []);
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget).entries()); if(data.website_confirm) return; setPhase("sending");
    try { const res = await fetch(`https://formsubmit.co/ajax/${SITE.email}`, { method:"POST", headers:{"Content-Type":"application/json",Accept:"application/json"}, body:JSON.stringify({...data,inquiry_type:type,flavor_interest:flavor,_subject:`Sip N Snack — ${type} — ${data.business}`,_template:"table",_captcha:"false"}) }); const result=await res.json(); if(!res.ok || (result.success !== true && result.success !== "true")) throw new Error("Rejected"); setPhase("sent"); } catch { setPhase("error"); }
  }
  return <div className="inquiry-card" id="inquiry"><noscript><style>{".inquiry-card form{display:none}"}</style><p>Please email <a href={`mailto:${SITE.email}`}>{SITE.email}</a> or message us on WhatsApp to request samples and pricing.</p></noscript>{phase === "sent" ? <div className="success" role="status"><Check size={40}/><h3>We have your request.</h3><p>We’ll contact you about product options, samples and delivery details.</p><button className="button dark" onClick={()=>setPhase("idle")}>Send another inquiry <ArrowRight size={18}/></button></div> : <form onSubmit={submit}>
    <div className="form-top"><span className="eyebrow">LET’S TALK CUPS</span><h3>Start with a conversation.</h3><p>Tell us a little about your business.</p></div>
    <label>I’m interested in<select value={type} onChange={e=>setType(e.target.value)} name="inquiry_type"><option>Sample request</option><option>Wholesale pricing</option><option>Event inquiry</option><option>Distribution partnership</option></select></label>
    <div className="form-grid"><label>Your name<input name="name" autoComplete="name" required placeholder="Full name"/></label><label>Business name<input name="business" autoComplete="organization" required placeholder="Company or venue"/></label></div>
    <div className="form-grid"><label>Email<input name="email" type="email" autoComplete="email" required placeholder="you@company.com"/></label><label>Phone<input name="phone" type="tel" autoComplete="tel" placeholder="Phone number"/></label></div>
    <div className="form-grid"><label>City / province<input name="location" required placeholder="Toronto, Ontario"/></label><label>Estimated quantity<select name="quantity"><option>Not sure yet</option><option>Under 500 cups</option><option>500–1,000 cups</option><option>1,000–5,000 cups</option><option>5,000–10,000 cups</option><option>10,000+ cups</option></select></label></div>
    <label>What are you planning?<textarea name="message" rows={3} placeholder="Business type, beverage, event date or delivery needs…"/></label>
    <div className="honeypot" aria-hidden="true"><label>Leave this empty<input name="website_confirm" tabIndex={-1} autoComplete="off"/></label></div>
    {phase === "error" && <p className="form-error" role="alert">We couldn’t send your request. Please <a href={`mailto:${SITE.email}`}>email us</a> or <a href={wa}>message us on WhatsApp</a>.</p>}
    <button className="button dark form-submit" disabled={phase === "sending"}>{phase === "sending" ? "Sending your request…" : "Send my request"}<ArrowUpRight size={18}/></button><p className="form-note">By submitting, you agree that we may contact you about this inquiry. <a href="/privacy">Privacy notice</a>.</p>
  </form>}</div>;
}

export default function Storefront() {
  const [mobile,setMobile]=useState(false); const [selected,setSelected]=useState(0); const [openFaq,setOpenFaq]=useState<number|null>(0); const f=flavors[selected];
  return <>
    <div className="announcement">A little sip. A little snack. <span>Edible cups for business · Canada + USA</span><a href="/wholesale">Explore wholesale <ArrowUpRight size={13}/></a></div>
    <header className="site-header"><div className="header-inner"><Brand/><nav className="desktop-nav" aria-label="Main navigation"><a href="#the-cup">The cup</a><details className="business-menu"><summary>For business <Plus size={12}/></summary><div><a href="/wholesale">Wholesale pricing</a>{segments.map(([t,h])=><a href={h} key={h}>{t}</a>)}</div></details><a href="#our-story">Our story</a><a href="#faq">FAQ</a></nav><a className="header-cta" href="#inquiry">Request a sample <ArrowUpRight size={16}/></a><button className="menu-button" aria-label={mobile?"Close menu":"Open menu"} aria-expanded={mobile} aria-controls="mobile-nav" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div>{mobile && <nav id="mobile-nav" className="mobile-nav" aria-label="Mobile navigation" onClick={()=>setMobile(false)}><a href="#the-cup">The cup</a><a href="/wholesale">Wholesale pricing</a>{segments.map(([t,h])=><a href={h} key={h}>{t}</a>)}<a href="#faq">FAQ</a><a href="#inquiry">Contact & samples</a></nav>}</header>
    <main>
      <section className="hero" id="the-cup"><div className="hero-copy"><span className="eyebrow"><span className="little-line"/> DRINK. ENJOY. EAT.</span><h1>The cup<br/>you can <em>eat.</em></h1><p className="hero-lead">Your favourite drink.<br/>A deliciously different finish.</p><p className="hero-body">Meet edible cups from Sip N Snack Co. Bring a sip-and-bite experience to your café, hotel or next celebration.</p><div className="hero-actions"><Cta>Request a sample</Cta><a className="text-link" href="/wholesale">Get wholesale pricing <ArrowRight size={17}/></a></div><div className="hero-footnote"><span className="tiny-cup"><Cookie size={19}/></span>Memorable coffee, chai & event moments.</div></div><div className="hero-visual"><img src="/images/hero-cup.jpg" alt="Illustrative edible cup filled with a latte" fetchPriority="high" width="1376" height="768"/><div className="hero-sticker">SIP FIRST.<span>SNACK AFTER.</span><Cookie size={24}/></div><div className="image-caption"><span>THE CUP IS PART OF THE EXPERIENCE</span><span>01 / SIP N SNACK</span></div><span className="photo-note">Product imagery is illustrative.</span></div></section>
      <div className="experience-strip"><span><Coffee/> POUR YOUR FAVOURITE</span><span><Cookie/> ENJOY THE LAST BITE</span><span><Package/> EXPLORE BUSINESS SUPPLY</span><span><MessageCircle/> ASK ABOUT SAMPLES</span></div>
      <section className="section why"><div className="section-heading"><span className="eyebrow">A SMALL TWIST. A DIFFERENT EXPERIENCE.</span><h2>More than a cup.<br/><em>A conversation starter.</em></h2><p>Turn an everyday drink into something worth remembering.</p></div><div className="why-grid">{[[Coffee,"Serve a little surprise.","Introduce an edible cup alongside the drinks your customers already enjoy."],[Cookie,"Make the last sip count.","When the drink is finished, the cup becomes part of the tasting experience."],[MessageCircle,"Find your business fit.","Start with a sample and review product information before adding cups to your menu."]].map(([Icon,t,p],i)=>{const I=Icon as typeof Coffee;return <article key={i}><span className="number">0{i+1}</span><I size={33}/><h3>{String(t)}</h3><p>{String(p)}</p></article>;})}</div></section>
      <section className="collection section" id="flavours"><div className="section-heading row-heading"><div><span className="eyebrow">FIND YOUR SIP & SNACK</span><h2>A flavour for<br/><em>your kind of moment.</em></h2></div><p>Explore vanilla, cardamom and chocolate.<br/>Ask about current options and availability.</p></div><div className="flavor-layout"><div className="flavor-photo"><img src={f.image} alt={`${f.name} edible cup flavour concept`} width="1376" height="768" loading="lazy"/><span className="flavor-photo-label">{f.name.toUpperCase()} / SIP N SNACK</span></div><div className="flavor-info"><span className="eyebrow">THE FLAVOUR COLLECTION</span><div className="flavor-tabs" role="tablist" aria-label="Explore flavours">{flavors.map((item,i)=><button key={item.name} id={`flavor-tab-${i}`} role="tab" aria-selected={selected===i} aria-controls="flavor-panel" tabIndex={selected===i?0:-1} onClick={()=>setSelected(i)} onKeyDown={e=>{if(e.key === "ArrowLeft" || e.key === "ArrowRight"){e.preventDefault();const n=(selected+(e.key === "ArrowRight"?1:2))%3;setSelected(n);document.getElementById(`flavor-tab-${n}`)?.focus();}}}>{item.name}</button>)}</div><div id="flavor-panel" role="tabpanel" aria-labelledby={`flavor-tab-${selected}`}><h3>{f.name}<em>{f.tag}</em></h3><p>{f.description}</p></div><div className="product-details"><p><span>Explore for</span><strong>Coffee, chai & celebrations</strong></p><p><span>Business supply</span><strong>Made to order</strong></p><p><span>Product information</span><strong>Available on request</strong></p></div><Cta>Ask about {f.name.toLowerCase()}</Cta><p className="product-note">Review ingredients, allergens, specifications and availability before ordering. Images illustrate flavour concepts.</p></div></div></section>
      <section className="how section"><div><span className="eyebrow">A NEW LITTLE RITUAL</span><h2>Three steps.<br/><em>One happy finish.</em></h2></div><div className="steps">{[["Pour.","Choose your beverage and review the cup’s serving specifications."],["Sip.","Enjoy the drink. Give the everyday coffee break a different twist."],["Bite.","Finish with the cup. That’s the Sip N Snack experience."]].map(([t,p],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{p}</p></article>)}</div></section>
      <section className="business section" id="business"><div className="business-intro"><div><span className="eyebrow">MADE FOR YOUR NEXT BUSINESS MOMENT</span><h2>Your next<br/><em>signature serve.</em></h2><p>From your morning café rush to a room full of guests, explore how edible cups could fit your service.</p><Cta href="/wholesale" light>Explore wholesale</Cta></div><div className="business-picture"><img src="/images/cafe.jpg" alt="Illustrative edible cup service in a café" width="1376" height="768" loading="lazy"/><span>CAFÉ SERVICE INSPIRATION · ILLUSTRATIVE IMAGE</span></div></div><div className="business-grid">{segments.map(([t,h,p],i)=><a href={h} key={h}><span className="business-index">0{i+1}</span><h3>{t}</h3><p>{p}</p><ArrowUpRight size={25}/></a>)}</div></section>
      <section className="story section" id="our-story"><div className="story-image"><img src="/images/bite.jpg" alt="Illustrative close-up of an edible cup with a bite from its rim" width="1376" height="768" loading="lazy"/><span className="story-label">A CUP. A SNACK.<br/><em>A little unexpected.</em></span></div><div className="story-copy"><span className="eyebrow">HELLO FROM SIP N SNACK CO.</span><h2>Small moments.<br/><em>Lasting impressions.</em></h2><p>We believe the way you serve a drink can be just as memorable as the drink itself.</p><p>Sip N Snack Co. brings edible cups made in India to business buyers in Canada and the USA, with a focus on cafés, hospitality and events in Toronto and the GTA.</p><p>We start with your needs: the beverage, the setting, the quantity and the guest experience. Then we help you explore the product and plan your next order.</p><a className="text-link" href="#inquiry">Let’s plan your next serve <ArrowRight size={18}/></a></div></section>
      <section className="faq section" id="faq"><div><span className="eyebrow">BEFORE YOUR FIRST BITE</span><h2>A few things<br/><em>you might ask.</em></h2><p>Need something more specific?<br/><a href={`mailto:${SITE.email}`}>Ask us directly <ArrowUpRight size={15}/></a></p></div><div className="faq-list">{faqs.map(([q,a],i)=><article key={q}><h3><button onClick={()=>setOpenFaq(openFaq===i?null:i)} aria-expanded={openFaq===i} aria-controls={`faq-answer-${i}`}>{q}{openFaq===i?<Minus size={18}/>:<Plus size={18}/>}</button></h3><div id={`faq-answer-${i}`} hidden={openFaq!==i}><p>{a}</p></div></article>)}</div></section>
      <section className="contact section" id="contact"><div className="contact-copy"><span className="eyebrow">YOUR NEXT SERVE STARTS HERE</span><h2>Let’s make<br/><em>it memorable.</em></h2><p>Request a sample, get a wholesale quote, or tell us about your next event.</p><div className="contact-options"><a href={wa}><MessageCircle size={20}/><span>Prefer a quick conversation?<strong>Message us on WhatsApp</strong></span><ArrowUpRight size={20}/></a><a href="tel:+16477031359"><Coffee size={20}/><span>Talk to Sip N Snack<strong>{SITE.phone}</strong></span><ArrowUpRight size={20}/></a></div><p className="contact-email"><a href={`mailto:${SITE.email}`}>{SITE.email}</a><br/>Toronto / GTA · Canada + USA</p></div><Inquiry flavor={f.name}/></section>
    </main>
    <footer className="site-footer"><div className="footer-top"><Brand/><p>Your favourite drink.<br/>A deliciously different finish.</p><a className="back-top" href="#the-cup">Back to top ↑</a></div><div className="footer-links"><div><span>EXPLORE</span><a href="#the-cup">The edible cup</a><a href="#flavours">Flavour collection</a><a href="#our-story">Our story</a><a href="#faq">FAQ</a></div><div><span>FOR BUSINESS</span><a href="/wholesale">Wholesale</a>{segments.map(([t,h])=><a href={h} key={h}>{t}</a>)}</div><div><span>LET’S CONNECT</span><a href={wa}>WhatsApp</a><a href={`mailto:${SITE.email}`}>{SITE.email}</a><a href="tel:+16477031359">{SITE.phone}</a><p>Toronto, Ontario · Canada</p></div></div><div className="footer-bottom"><span>© 2026 Sip N Snack Co. · Bite • Sip • Smile.</span><span><a href="/privacy">Privacy</a> · Product imagery is illustrative.</span></div></footer>
    <div className="mobile-sticky"><a href={wa} aria-label="Message Sip N Snack on WhatsApp"><MessageCircle size={22}/></a><a href="#inquiry">Request a sample <ArrowUpRight size={18}/></a></div>
  </>;
}
