import { readFile, writeFile } from "node:fs/promises";

const pages = {
  wholesale: {
    title: "Wholesale Edible Cups in Canada & USA", eyebrow: "BUSINESS SUPPLY, WITH A DIFFERENT FINISH", heading: "Wholesale cups.\nFor commercial service.", image: "flatlay.jpg", interest: "Wholesale pricing",
    description: "Explore wholesale edible cups for cafés, hotels, caterers and business buyers in Canada and the USA. Request samples and a tailored quote from Sip N Snack Co.",
    intro: "Edible cups for the businesses that make everyday moments memorable. Tell us what you serve, how many cups you need and where you need them.",
    sections: [
      ["Start with the right product", "Your beverage, service style and customer experience come first. Request current specifications, ingredient and allergen information, and samples before selecting a cup for your menu. Explore vanilla, cardamom and chocolate flavour directions and confirm availability with us."],
      ["Plan your business order", "Share your estimated quantity, business location, desired delivery date and whether you need a one-time order or ongoing supply. Our cups are made to order. We will confirm current product options, pricing, lead time, delivery arrangements and payment terms in your quote."],
      ["A practical path to your first serve", "First, send your requirements. Next, evaluate the product and review the specifications for your use. Then confirm the quote and delivery plan. This lets you introduce edible cups into your service with a clear understanding of what you are ordering."],
    ],
    questions: [["Who can request wholesale pricing?", "Cafés, chai shops, hotels, restaurants, caterers, event planners, wholesalers and distributors may inquire about business supply."], ["Can we evaluate a sample?", "Yes. Request sample availability and delivery details for your location before planning a larger order."], ["Where do you supply?", "We welcome business inquiries from Toronto, the GTA, Ontario, other Canadian locations and the USA. Delivery and import arrangements are confirmed for each order."]],
  },
  cafes: {
    title: "Edible Cups for Cafés & Chai Shops", eyebrow: "SOMETHING NEW FOR YOUR REGULARS", heading: "Edible cups.\nFor café operators.", image: "cafe.jpg", interest: "Wholesale pricing",
    description: "Explore edible coffee and chai cups for cafés, coffee shops and beverage businesses in Toronto, Ontario, Canada and the USA. Request samples and business pricing.",
    intro: "Give your next coffee or chai service a sip-and-bite twist. Explore edible cups as a new serving option for your café and the people who keep coming back.",
    sections: [["Find your menu fit", "Tell us about the drinks you serve and the experience you want to create. Review cup specifications for your beverage and service conditions, then evaluate samples with your team before launching. Ingredient and allergen information should be part of that review."], ["Explore your flavour direction", "Vanilla, cardamom and chocolate offer different directions for a café tasting experience. Ask about current options and availability. Consider how the cup complements your existing drinks and how you will describe it to customers."], ["Plan a trial, then plan supply", "A smaller introduction can help you understand customer interest and your service workflow. Share your estimated quantity, expected monthly use and location so we can discuss a quote and made-to-order supply. Confirm delivery timing before adding cups to a promoted menu offer."]],
    questions: [["What should we include in a café inquiry?", "Your business name, location, beverage type, expected quantity and desired start date help us prepare a useful response."], ["Can I use them for hot chai?", "Request the current serving specifications and test a sample under your own beverage and service conditions."], ["Are dietary details available?", "Request current ingredients and allergens for the exact product before making vegan, gluten-free or other dietary statements on your menu."]],
  },
  events: {
    title: "Edible Cups for Events & Catering", eyebrow: "ONE MORE THING THEY’LL REMEMBER", heading: "Edible cups.\nFor professional catering.", image: "flatlay.jpg", interest: "Event inquiry",
    description: "Wholesale edible cups for catering businesses, professional event planners and corporate event teams in Toronto, the GTA, Canada and the USA. Discuss samples, quantities and delivery dates.",
    intro: "Wholesale edible cups for professional catering operations, corporate event teams and commercial event planners. Coordinate your beverage service, order quantity and delivery timeline.",
    sections: [["Design the serving moment", "Tell us how your guests will enjoy their drinks: a staffed coffee station, a catered meal, a reception or a corporate gathering. Review product suitability with your beverage provider and plan how the edible cup will be introduced to guests."], ["Coordinate with your service team", "Your catering and venue teams can assess service conditions, handling and allergen communication. Request samples and current product details before committing the cups to your event plan. Share any venue or catering requirements in your inquiry."], ["Work back from the event date", "Our cups are made to order, so timing matters. Include your event date, venue city, guest count, estimated cups and beverage choice. We will discuss availability, delivery arrangements and a quote. Confirm the delivery plan before advertising the cups as part of your event."]],
    questions: [["What events can inquire?", "Wedding planners, caterers, corporate event teams, conference organizers and professional event organizers may contact us."], ["What quantity should I request?", "Tell us your guest count and how the drinks will be served. The estimated number of cups helps us prepare the quote."], ["Can you guarantee delivery for my date?", "Delivery dates and availability must be confirmed with your order. Please include the event date in your first inquiry."]],
  },
  hospitality: {
    title: "Edible Cups for Hotels & Hospitality", eyebrow: "A DIFFERENT DETAIL IN YOUR GUEST EXPERIENCE", heading: "Edible cups.\nFor hospitality teams.", image: "cafe.jpg", interest: "Wholesale pricing",
    description: "Explore edible cups for hotels, hospitality teams, restaurants and banquet service in Canada and the USA. Request product information, samples and business pricing.",
    intro: "Explore edible cups as a new detail in your hotel café, banquet service or guest hospitality. Start with the service moment you want to create.",
    sections: [["Explore with your service team", "Bring your food and beverage, purchasing and operations teams into the evaluation. Share the proposed beverage and serving environment so you can review the right product information and assess samples before introducing the cups to guests."], ["Plan around your service", "Consider beverage preparation, presentation, storage and staff instructions. Request current specifications and ingredient and allergen information for your operational review. Samples can help your team assess whether the cup fits your proposed use."], ["Coordinate business supply", "Tell us your property location, purchasing contact, estimated quantity and preferred delivery timeline. For recurring requirements, share expected monthly use. We will discuss made-to-order supply, current options, delivery arrangements and commercial terms in your quote."]],
    questions: [["Who should submit the inquiry?", "A food and beverage, purchasing, events or operations contact can share your property’s requirements."], ["Can we review product documents?", "Request current product specifications, ingredient and allergen details with your inquiry."], ["Can we discuss repeat orders?", "Yes. Share estimated monthly quantities and delivery needs so we can discuss supply arrangements."]],
  },
  distributors: {
    title: "Edible Cup Distribution & Wholesale Partners", eyebrow: "LET’S EXPLORE THE NEXT OPPORTUNITY", heading: "A new product.\nFor the businesses you serve.", image: "flatlay.jpg", interest: "Distribution partnership",
    description: "Explore edible cup distribution with Sip N Snack Co. Foodservice wholesalers, packaging distributors and resellers in Canada and the USA can inquire about partnership options.",
    intro: "Add a new conversation to your product range. We welcome inquiries from distributors and wholesalers serving cafés, hospitality, catering and event businesses.",
    sections: [["Tell us about your market", "Share the territory you cover, the business customers you serve and your existing product categories. Foodservice, packaging and hospitality channels have different needs; understanding your customer base helps us discuss where edible cups could fit."], ["Evaluate the product opportunity", "Request current product specifications, ingredients, allergens and sample availability before presenting the cups to customers. Share the formats, order quantities and support information your buyers typically require."], ["Discuss the commercial arrangement", "Include your estimated volume, storage and delivery capabilities, business location and contact details. We will discuss current availability, made-to-order supply and potential terms. Territory, exclusivity and distribution pricing are subject to a specific agreement and are not assumed."]],
    questions: [["Who can inquire about distribution?", "Foodservice wholesalers, packaging distributors, hospitality suppliers and resellers may contact us."], ["What details should we send?", "Your territory, customer segments, current categories, estimated volume and supply requirements will help us assess the opportunity."], ["Are exclusive territories available?", "Any territory rights or exclusivity require a specific discussion and agreement. No exclusivity is offered through this website alone."]],
  },
};
const escape = s => s.replaceAll("&", "&amp;").replaceAll('"', "&quot;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
const nav = `<header class="site-header"><div class="header-inner"><a class="brand" href="/"><span class="brand-mark">S</span><span>Sip N Snack<span class="brand-co">CO. · BITE • SIP • SMILE</span></span></a><nav class="landing-nav" aria-label="Business navigation"><a href="/">Home</a><a href="/wholesale">Wholesale</a><a href="/cafes">Cafés</a><a href="/events">Events</a><a href="/hospitality">Hotels</a><a href="/distributors">Distributors</a></nav></div></header>`;
const footer = `<footer class="site-footer"><div class="footer-bottom"><span>© 2026 Sip N Snack Co. · Bite • Sip • Smile.</span><a href="/privacy">Privacy</a><a href="mailto:sipnsnack786@gmail.com">sipnsnack786@gmail.com</a></div></footer>`;
const head = (route, title, description) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} | Sip N Snack Co.</title><meta name="description" content="${escape(description)}"><meta name="robots" content="index,follow"><link rel="canonical" href="https://www.sipnsnackco.ca/${route}"><meta property="og:type" content="website"><meta property="og:title" content="${escape(title)} | Sip N Snack Co."><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="https://www.sipnsnackco.ca/${route}"><meta property="og:image" content="https://www.sipnsnackco.ca/images/hero-cup.jpg"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/storefront.css"></head><body><div class="announcement">Bite • Sip • Smile. <span>Serving business buyers in Canada + USA</span></div>${nav}`;
await writeFile("public/storefront.css", await readFile("storefront.css", "utf8"));
for (const [route,p] of Object.entries(pages)) {
  const cta = `/?interest=${encodeURIComponent(p.interest)}#inquiry`;
  const html = `${head(route,p.title,p.description)}<main><section class="hero landing-hero"><div class="hero-copy"><span class="eyebrow">${p.eyebrow}</span><h1>${p.heading.split("\n").map(escape).join("<br>")}</h1><p class="hero-body">${p.intro}</p><a class="button dark" href="${cta}">Request a business quote ↗</a></div><div class="hero-visual"><img src="/images/${p.image}" alt="Illustrative edible cup presentation for business service" width="1376" height="768"><span class="photo-note">Product imagery is illustrative.</span></div></section><section class="section landing-content"><span class="eyebrow">${escape(p.title.toUpperCase())}</span>${p.sections.map(([h,b])=>`<article><h2>${h}</h2><p>${b}</p></article>`).join("")}</section><section class="section landing-faq"><h2>Before your first order.</h2>${p.questions.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join("")}</section><section class="section landing-cta"><span class="eyebrow">LET’S TALK ABOUT YOUR REQUIREMENTS</span><h2>Your next serve<br><em>starts here.</em></h2><p>Tell us your business, location, quantity and timeline.</p><a class="button dark" href="${cta}">${p.interest === "Distribution partnership" ? "Discuss a partnership" : "Request product information"} ↗</a><a class="text-link" href="tel:+16477031359">Call 647-703-1359 →</a></section></main>${footer}</body></html>`;
  await writeFile(`public/${route}.html`,html);
}
await writeFile("public/privacy.html", `${head("privacy","Inquiry Privacy Notice","How Sip N Snack Co. handles information submitted through its business inquiry form.")}<main class="section landing-content privacy-content"><span class="eyebrow">SIP N SNACK CO.</span><h1>Inquiry privacy notice.</h1><p>Effective October 10, 2026.</p><article><h2>Information you submit</h2><p>The business inquiry form collects your name, business name and type, optional role and website, email address, optional phone number, location, country, estimated order quantity, supply requirement, inquiry type, flavour interest and message. Please do not submit payment card details or other sensitive information through this form.</p></article><article><h2>How your inquiry is used</h2><p>Sip N Snack Co. uses this information to respond to your request and discuss product options, samples, quotes and delivery. This form does not subscribe you to a marketing mailing list.</p></article><article><h2>Form delivery and external services</h2><p>Form submissions are sent through FormSubmit, a third-party form delivery provider, to Sip N Snack Co. Contacting us by email or WhatsApp uses those services and their own privacy practices. Google Fonts supplies website fonts and may receive technical connection information from your browser.</p></article><article><h2>Questions or requests</h2><p>Contact sipnsnack786@gmail.com to ask about your inquiry information, request a correction or request deletion of information you submitted. Information needed to fulfill an order or meet applicable obligations may need to be retained.</p></article><a class="button dark" href="/">Back to Sip N Snack ↗</a></main>${footer}</body></html>`);
const routes=[...Object.keys(pages),"privacy"];
await writeFile("public/_redirects",routes.map(r=>`/${r}.html /${r} 301\n/${r} /${r}.html 200`).join("\n")+"\n");
